export const work_hour_data = [
	{
		Date: '04-01-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '01-02-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '02-02-2026',
		Day: 'Monday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '02-02-2026',
		Day: 'Monday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '03-02-2026',
		Day: 'Tuesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '03-02-2026',
		Day: 'Tuesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '04-02-2026',
		Day: 'Wednesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '04-02-2026',
		Day: 'Wednesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '05-02-2026',
		Day: 'Thursday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '05-02-2026',
		Day: 'Thursday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '06-02-2026',
		Day: 'Friday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '06-02-2026',
		Day: 'Friday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '07-02-2026',
		Day: 'Saturday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '07-02-2026',
		Day: 'Saturday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '08-02-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '08-02-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '09-02-2026',
		Day: 'Monday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '09-02-2026',
		Day: 'Monday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '10-02-2026',
		Day: 'Tuesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '10-02-2026',
		Day: 'Tuesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '11-02-2026',
		Day: 'Wednesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '11-02-2026',
		Day: 'Wednesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '12-02-2026',
		Day: 'Thursday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '12-02-2026',
		Day: 'Thursday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '13-02-2026',
		Day: 'Friday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '13-02-2026',
		Day: 'Friday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '14-02-2026',
		Day: 'Saturday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '14-02-2026',
		Day: 'Saturday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '15-02-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '15-02-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '16-02-2026',
		Day: 'Monday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '16-02-2026',
		Day: 'Monday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '17-02-2026',
		Day: 'Tuesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '17-02-2026',
		Day: 'Tuesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '18-02-2026',
		Day: 'Wednesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '18-02-2026',
		Day: 'Wednesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '19-02-2026',
		Day: 'Thursday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '19-02-2026',
		Day: 'Thursday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '20-02-2026',
		Day: 'Friday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '20-02-2026',
		Day: 'Friday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '21-02-2026',
		Day: 'Saturday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '21-02-2026',
		Day: 'Saturday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '22-02-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '22-02-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '23-02-2026',
		Day: 'Monday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '23-02-2026',
		Day: 'Monday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '24-02-2026',
		Day: 'Tuesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '24-02-2026',
		Day: 'Tuesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '25-02-2026',
		Day: 'Wednesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '25-02-2026',
		Day: 'Wednesday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '26-02-2026',
		Day: 'Thursday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '26-02-2026',
		Day: 'Thursday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '27-02-2026',
		Day: 'Friday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '27-02-2026',
		Day: 'Friday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 0
	},
	{
		Date: '28-02-2026',
		Day: 'Saturday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '28-02-2026',
		Day: 'Saturday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	},
	{
		Date: '01-03-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 1',
		Line: 'Line 1',
		Manpower: 11,
		Efficiency: 60,
		WorkHour: 10
	},
	{
		Date: '01-03-2026',
		Day: 'Sunday',
		Shift: 'Day Shift',
		Section: 'Sewing',
		Floor: 'Floor 2',
		Line: 'Line 2',
		Manpower: 19,
		Efficiency: 60,
		WorkHour: 11
	}
];
